spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/templates/


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-intranetdb.cgydu6nogwyk.us-east-1.rds.amazonaws.com:3306/intranetDB?serverTimezone=UTC&useSSL=false
    #url: jdbc:mysql://localhost:3306/intranetDB?serverTimezone=UTC&useSSL=false
    username: admin
    password: ppp20875801

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    com.jpa.student: debug
    #org.hibernate.SQL: debug
    #org.hibernate.type: trace

server:
  port: 8086
  servlet:
    encoding:
      force-response: true

resource:
  path:  file:///C:/profile/

upload:
  path: /C:/profile/**



